### ISSUE TITLE
Calculation issue

### ISSUE THREAD

**Issue by iconbetdev420** [iconbet/iconbet-java-scores#6]
https://github.com/iconbet/iconbet-java-scores/blob/ec0e46f31a447df59a45e93d0d53bddafa99bbf1/daodice-score/src/main/java/com/iconbet/score/daodice/DaoDice.java#L332

I find the bug during the calculation on BigNumber. If you use ```.divide(2) prior then it will be only 1*gap*100 ``` 
Please confirm this fix.

```BigInteger main_bet_limit =
				_treasury_min.multiply(BigInteger.valueOf(3)).multiply(gap).multiply(_100)
				.divide( BigInteger.valueOf((long) (2 * _100 * (_68134 - _681_34 * gap.intValue()) )));```

**Comment by iconbetdev420** [comment]
@ismaelmk @cacomixtle

**Comment by cacomixtle** [comment]
The bug is invalid: 

i am not making 3 / 2 = 1  (integer division)

i am making:
(_treasury_min * 3 ) / 2 

but moving 2 to denominator is a valid reduction, i will apply it
